name: Upload nix cache
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    name: Build and upload cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up cachix
        uses: cachix/cachix-action@v15
        with:
          name: rofi-jetbrains
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build nix packages
        run: |
          nix build .#rofi-jetbrains .#rofi-jetbrains-next
